name: music_finder
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  discover:
    path: feature/discover
  core:
    path: util/core
  design_system:
    path: util/design_system
  auto_route: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  linter:
    path: util/linter

flutter:
  uses-material-design: true
