name: core
description: A new Flutter package project.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.0.3
  freezed: ^2.0.3+1
  get_it: ^7.2.0
  i69n: ^2.1.0
  injectable: ^1.5.3
  retrofit: ^3.0.1+1

dev_dependencies:
  build_runner: ^2.1.11
  flutter_test:
    sdk: flutter
  linter:
    path: ../linter
  injectable_generator: ^1.5.3