name: bdd
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  core:
    path: ../core
  design_system:
    path: ../design_system
  dio: ^4.0.6
dev_dependencies:
  linter:
    path: ../linter
  mocktail: ^0.3.0